#!/usr/bin/env bash
# HealthGuard — One-command setup
# Usage: bash setup.sh
set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════╗"
echo "║        HealthGuard — Setup Script        ║"
echo "╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── Check dependencies ────────────────────────────────────────────────────────
echo -e "${CYAN}[1/5] Checking dependencies...${NC}"
for cmd in docker python3; do
  if ! command -v $cmd &>/dev/null; then
    echo -e "${RED}✗ '$cmd' not found. Please install it first.${NC}"
    exit 1
  fi
done
if ! docker compose version &>/dev/null; then
  echo -e "${RED}✗ 'docker compose' plugin not found.${NC}"
  exit 1
fi
echo -e "${GREEN}✓ docker and python3 found${NC}"

# ── Generate .env if missing ──────────────────────────────────────────────────
echo -e "${CYAN}[2/5] Configuring environment...${NC}"

ENV_FILE="./backend/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}  Generating secrets...${NC}"

  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
  ENCRYPTION_KEY=$(python3 -c "import base64, os; print(base64.b64encode(os.urandom(32)).decode())")

  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date)
APP_NAME=HealthGuard API
ENVIRONMENT=development
DEBUG=false

DATABASE_URL=postgresql://postgres:postgres@db:5432/healthguard

SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=7

MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION_MINUTES=15
BCRYPT_ROUNDS=12
RATE_LIMIT_PER_MINUTE=60
MAX_UPLOAD_SIZE_MB=50
MAX_RECORDS_PER_UPLOAD=10000

ALLOWED_ORIGINS=["http://localhost:5173","http://localhost:3000"]
EOF
  echo -e "${GREEN}  ✓ .env created with fresh secrets${NC}"
else
  echo -e "${GREEN}  ✓ .env already exists, skipping${NC}"
fi

# ── Build & start containers ──────────────────────────────────────────────────
echo -e "${CYAN}[3/5] Starting containers (this may take a few minutes on first run)...${NC}"
docker compose up -d --build

# ── Wait for backend health ────────────────────────────────────────────────────
echo -e "${CYAN}[4/5] Waiting for services to be ready...${NC}"
MAX_WAIT=60
WAITED=0
until curl -sf http://localhost:8000/api/health > /dev/null 2>&1; do
  sleep 2
  WAITED=$((WAITED + 2))
  echo -ne "  Waited ${WAITED}s...\r"
  if [ $WAITED -ge $MAX_WAIT ]; then
    echo -e "${RED}✗ Backend did not start within ${MAX_WAIT}s. Check: docker compose logs backend${NC}"
    exit 1
  fi
done

# ── Seed database (roles, locations, teams, demo users, sample patients) ──────
echo -e "\n${CYAN}[5/5] Seeding database...${NC}"
docker compose --profile seed run --rm seeder
echo -e "${GREEN}✓ Database seed complete${NC}"

echo -e "\n${GREEN}"
echo "╔══════════════════════════════════════════════╗"
echo "║           HealthGuard is ready! 🎉           ║"
echo "╠══════════════════════════════════════════════╣"
echo "║  Frontend:  http://localhost:5173            ║"
echo "║  API Docs:  http://localhost:8000/api/docs   ║"
echo "╠══════════════════════════════════════════════╣"
echo "║  Admin:     admin         / Admin@123!       ║"
echo "║  Manager:   mgr_us        / Manager@123!     ║"
echo "║  User:      user_us_ar    / User@1234!       ║"
echo "╚══════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "Stop with: ${CYAN}docker compose down${NC}"
echo -e "Logs with: ${CYAN}docker compose logs -f${NC}"
